# Generated by Django 5.1.1 on 2024-10-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('RPG', 'Role-playing (RPG)')], max_length=100, null=True),
        ),
    ]
