# Generated by Django 5.1.1 on 2024-10-09 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapor', '0002_alter_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
