# Generated by Django 5.1.1 on 2024-10-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapor', '0004_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
    ]
