# Generated by Django 5.1.1 on 2024-10-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapor', '0006_game_slug_alter_rating_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
