# Generated by Django 5.1.1 on 2024-10-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapor', '0007_game_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='publishers',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
